In [14]:
import numpy as np

y = np.array([1, 2, 1, 0])
X = np.arange(16).reshape(4,4)
print(y,'\n', X)
index_data = np.argsort(y) #index_data: (N,)
print(index_data)
y_sorted = y[index_data]
vals, idx_start, count = np.unique(y_sorted, return_counts=True,
                                return_index=True)
print(X.T[:,idx_start])
X_sorted_split= np.split(X.T[:,index_data], idx_start[1:], axis=1)
print(X_sorted_split[idx_start])
print(np.shape(X_sorted_split[2]))
print(np.ndarray.array(X_sorted_split))
print(np.sum(X_sorted_split, axis=1))
# X_sorted_split_sum = np.concatenate(np.sum(X_sorted_split, axis=1))
print(X_sorted_split_sum)

[1 2 1 0] 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[3 0 2 1]
[[ 0  4 12]
 [ 1  5 13]
 [ 2  6 14]
 [ 3  7 15]]


TypeError: only integer scalar arrays can be converted to a scalar index