In [19]:
import numpy as np

x = np.array([[1,0,-2], [0,2,0], [1,-1,0], [-3, 2, 4]])
w = np.array([[1,0,-2], [0,2,0], [1,-1,0]])
margin = x.dot(w)
print(margin)
margin[margin==1] = 0
margin[margin<0] = 0
print(margin)
margin[np.nonzero(margin)]

[[-1  2 -2]
 [ 0  4  0]
 [ 1 -2 -2]
 [ 1  0  6]]
[[0 2 0]
 [0 4 0]
 [0 0 0]
 [0 0 6]]


array([2, 4, 6])

In [18]:
dW = np.zeros((np.shape(x)[0], np.shape(x)[1], np.shape(w)[0])
dW[np.nonzero(margin), :] = X[np.nonzero(margin)[1]]

SyntaxError: invalid syntax (<ipython-input-18-e74dc1d9541b>, line 2)